sudo: false

language: php

matrix: 
  fast_finish: true
  include:
    - php: 7.1
      env:
        EXECUTE_COVERAGE=true

before_install:
  - if [[ $EXECUTE_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/phpcs; fi

